/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ViewOverviewExtJS4.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.panel.Tool',
        'Ext.grid.View',
        'Ext.grid.column.Number',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.Date',
        'Ext.form.field.File',
        'Ext.form.field.HtmlEditor',
        'Ext.form.field.Number',
        'Ext.form.field.Radio',
        'Ext.form.field.TextArea',
        'Ext.form.field.Time',
        'Ext.menu.Separator',
        'Ext.menu.CheckItem',
        'Ext.menu.ColorPicker',
        'Ext.menu.DatePicker',
        'Ext.ProgressBar',
        'Ext.toolbar.Separator',
        'Ext.button.Cycle',
        'Ext.tree.Panel',
        'Ext.tree.View',
        'Ext.toolbar.Paging',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Display',
        'Ext.form.Label',
        'Ext.form.RadioGroup',
        'Ext.slider.Single',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.grid.property.Grid',
        'Ext.grid.plugin.RowExpander',
        'Ext.XTemplate'
    ],

    autoScroll: true,
    layout: 'absolute',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    x: 10,
                    y: 10,
                    height: 150,
                    maxWidth: 150,
                    title: 'Regular Panel',
                    tools: [
                        {
                            xtype: 'tool'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    x: 170,
                    y: 10,
                    frame: true,
                    height: 150,
                    width: 150,
                    title: 'Framed Panel',
                    tools: [
                        {
                            xtype: 'tool'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    x: 330,
                    y: 10,
                    height: 200,
                    width: 150,
                    collapsed: true,
                    collapsible: true,
                    title: 'Collapsed Panel'
                },
                {
                    xtype: 'panel',
                    x: 330,
                    y: 80,
                    frame: true,
                    height: 150,
                    width: 150,
                    collapsed: true,
                    collapsible: true,
                    title: 'Collapsed Framed'
                },
                {
                    xtype: 'gridpanel',
                    x: 10,
                    y: 170,
                    height: 150,
                    width: 310,
                    title: 'Grid Panel',
                    store: 'peopleStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'name',
                            text: 'Name'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'gender',
                            text: 'Gender'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'age',
                            text: 'Age'
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    x: 490,
                    y: 10,
                    height: 150,
                    width: 200,
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            title: 'Tab 1'
                        },
                        {
                            xtype: 'panel',
                            title: 'Tab 2'
                        },
                        {
                            xtype: 'panel',
                            title: 'Tab 3',
                            tabConfig: {
                                xtype: 'tab',
                                disabled: true
                            }
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    x: 700,
                    y: 10,
                    frame: true,
                    height: 150,
                    width: 200,
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            title: 'Tab 1'
                        },
                        {
                            xtype: 'panel',
                            title: 'Tab 2'
                        },
                        {
                            xtype: 'panel',
                            title: 'Tab 3',
                            tabConfig: {
                                xtype: 'tab',
                                disabled: true
                            }
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    x: 910,
                    y: 10,
                    height: 150,
                    width: 200,
                    activeTab: 0,
                    plain: true,
                    items: [
                        {
                            xtype: 'panel',
                            title: 'Tab 1'
                        },
                        {
                            xtype: 'panel',
                            title: 'Tab 2'
                        },
                        {
                            xtype: 'panel',
                            title: 'Tab 3',
                            tabConfig: {
                                xtype: 'tab',
                                disabled: true
                            }
                        }
                    ]
                },
                {
                    xtype: 'checkboxfield',
                    x: 10,
                    y: 330,
                    fieldLabel: 'Checkbox'
                },
                {
                    xtype: 'checkboxfield',
                    x: 150,
                    y: 330,
                    fieldLabel: 'Checkbox',
                    checked: true
                },
                {
                    xtype: 'combobox',
                    x: 10,
                    y: 360,
                    fieldLabel: 'ComboBox',
                    store: [
                        'icecream',
                        'chocolate',
                        'popcorn'
                    ]
                },
                {
                    xtype: 'datefield',
                    x: 10,
                    y: 390,
                    fieldLabel: 'Date Field'
                },
                {
                    xtype: 'filefield',
                    x: 10,
                    y: 420,
                    fieldLabel: 'File Upload'
                },
                {
                    xtype: 'htmleditor',
                    x: 10,
                    y: 450,
                    height: 150,
                    width: 650,
                    fieldLabel: 'HTML Editor'
                },
                {
                    xtype: 'multislider',
                    x: 10,
                    y: 610,
                    width: 400,
                    fieldLabel: 'Multi Slider',
                    values: [
                        10,
                        40
                    ]
                },
                {
                    xtype: 'numberfield',
                    x: 10,
                    y: 640,
                    fieldLabel: 'Number Field'
                },
                {
                    xtype: 'radiofield',
                    x: 10,
                    y: 670,
                    fieldLabel: 'Radio'
                },
                {
                    xtype: 'radiofield',
                    x: 150,
                    y: 670,
                    fieldLabel: 'Radio',
                    checked: true
                },
                {
                    xtype: 'textareafield',
                    x: 10,
                    y: 700,
                    fieldLabel: 'Text Area'
                },
                {
                    xtype: 'textfield',
                    x: 330,
                    y: 700,
                    fieldLabel: 'Text Field'
                },
                {
                    xtype: 'timefield',
                    x: 330,
                    y: 670,
                    fieldLabel: 'Time Field'
                },
                {
                    xtype: 'triggerfield',
                    x: 330,
                    y: 640,
                    fieldLabel: 'Trigger Field'
                },
                {
                    xtype: 'menu',
                    x: 680,
                    y: 650,
                    floating: false,
                    width: 120,
                    items: [
                        {
                            xtype: 'menuitem',
                            text: 'Menu Item'
                        },
                        {
                            xtype: 'menuitem',
                            disabled: true,
                            text: 'Menu Item'
                        },
                        {
                            xtype: 'menuseparator'
                        },
                        {
                            xtype: 'menucheckitem',
                            text: 'Menu Item'
                        },
                        {
                            xtype: 'menucheckitem',
                            text: 'Menu Item',
                            checked: true
                        }
                    ]
                },
                {
                    xtype: 'colormenu',
                    x: 620,
                    y: 170,
                    floating: false,
                    height: 150,
                    width: 150
                },
                {
                    xtype: 'datemenu',
                    x: 780,
                    y: 170,
                    floating: false,
                    width: 300
                },
                {
                    xtype: 'button',
                    x: 680,
                    y: 450,
                    text: 'Small Button'
                },
                {
                    xtype: 'button',
                    x: 680,
                    y: 600,
                    disabled: true,
                    text: 'Disabled Button'
                },
                {
                    xtype: 'button',
                    x: 680,
                    y: 490,
                    scale: 'medium',
                    text: 'Medium Button'
                },
                {
                    xtype: 'button',
                    x: 680,
                    y: 540,
                    scale: 'large',
                    text: 'Large Button'
                },
                {
                    xtype: 'progressbar',
                    x: 570,
                    y: 390,
                    width: 200,
                    value: 0.4
                },
                {
                    xtype: 'toolbar',
                    x: 10,
                    y: 780,
                    maxWidth: 850,
                    items: [
                        {
                            xtype: 'button',
                            text: 'Small Button'
                        },
                        {
                            xtype: 'button',
                            scale: 'medium',
                            text: 'Medium Button'
                        },
                        {
                            xtype: 'button',
                            scale: 'large',
                            text: 'Large Button'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            text: 'Disabled Button'
                        },
                        {
                            xtype: 'cycle',
                            showText: true,
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menucheckitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menucheckitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menucheckitem',
                                        text: 'Menu Item'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'splitbutton',
                            text: 'Split Button'
                        }
                    ]
                },
                {
                    xtype: 'treepanel',
                    x: 370,
                    y: 170,
                    height: 200,
                    width: 200,
                    title: 'Tree Panel',
                    store: 'MyTreeStore',
                    viewConfig: {

                    }
                },
                {
                    xtype: 'cycle',
                    x: 840,
                    y: 450,
                    showText: true,
                    menu: {
                        xtype: 'menu',
                        width: 120,
                        items: [
                            {
                                xtype: 'menucheckitem',
                                text: 'Menu Item'
                            },
                            {
                                xtype: 'menucheckitem',
                                text: 'Menu Item'
                            },
                            {
                                xtype: 'menucheckitem',
                                text: 'Menu Item'
                            }
                        ]
                    }
                },
                {
                    xtype: 'splitbutton',
                    x: 840,
                    y: 490,
                    text: 'Split Button'
                },
                {
                    xtype: 'button',
                    x: 10,
                    y: 960,
                    text: 'MyButton'
                },
                {
                    xtype: 'cycle',
                    x: 950,
                    y: 450,
                    showText: true,
                    menu: {
                        xtype: 'menu',
                        width: 120,
                        items: [
                            {
                                xtype: 'menucheckitem',
                                text: 'Menu Item'
                            },
                            {
                                xtype: 'menucheckitem',
                                text: 'Menu Item'
                            },
                            {
                                xtype: 'menucheckitem',
                                text: 'Menu Item'
                            }
                        ]
                    }
                },
                {
                    xtype: 'splitbutton',
                    x: 10,
                    y: 930,
                    text: 'MyButton'
                },
                {
                    xtype: 'toolbar',
                    x: 780,
                    y: 390
                },
                {
                    xtype: 'pagingtoolbar',
                    x: 820,
                    y: 530,
                    width: 360,
                    displayInfo: true
                },
                {
                    xtype: 'fieldcontainer',
                    x: 1100,
                    y: 170,
                    height: 120,
                    width: 400,
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'form',
                    x: 820,
                    y: 580,
                    bodyPadding: 10,
                    title: 'My Form',
                    items: [
                        {
                            xtype: 'fieldset',
                            title: 'My Fields',
                            items: [
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    anchor: '100%',
                                    fieldLabel: 'Label',
                                    boxLabel: 'Box Label'
                                },
                                {
                                    xtype: 'checkboxgroup',
                                    fieldLabel: 'Label',
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            boxLabel: 'Box Label'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            boxLabel: 'Box Label'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'displayfield',
                                    anchor: '100%',
                                    fieldLabel: 'Label',
                                    value: 'Display Field'
                                },
                                {
                                    xtype: 'filefield',
                                    anchor: '100%',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'htmleditor',
                                    anchor: '100%',
                                    height: 150,
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'label',
                                    text: 'My Label'
                                },
                                {
                                    xtype: 'multislider',
                                    anchor: '100%',
                                    fieldLabel: 'Label',
                                    values: [
                                        10,
                                        40
                                    ]
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'radiofield',
                                    anchor: '100%',
                                    fieldLabel: 'Label',
                                    boxLabel: 'Box Label'
                                },
                                {
                                    xtype: 'radiogroup',
                                    fieldLabel: 'Label',
                                    items: [
                                        {
                                            xtype: 'radiofield',
                                            boxLabel: 'Box Label'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            boxLabel: 'Box Label'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'slider',
                                    anchor: '100%',
                                    fieldLabel: 'Label',
                                    value: 40
                                },
                                {
                                    xtype: 'textareafield',
                                    anchor: '100%',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'timefield',
                                    anchor: '100%',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'triggerfield',
                                    anchor: '100%',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'progressbar',
                                    value: 0.4
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    x: 100,
                    y: 830,
                    height: 170,
                    width: 710,
                    title: 'My Grid Panel',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'String'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'number',
                            text: 'Number'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'date',
                            text: 'Date'
                        },
                        {
                            xtype: 'booleancolumn',
                            dataIndex: 'bool',
                            text: 'Boolean'
                        }
                    ]
                },
                {
                    xtype: 'propertygrid',
                    x: 100,
                    y: 1010,
                    width: 710,
                    title: 'My Property Grid',
                    source: {
                        'Property 1': 'String',
                        'Property 2': true,
                        'Property 3': '2018-02-26T22:15:02',
                        'Property 4': 123
                    },
                    plugins: [
                        Ext.create('Ext.grid.plugin.RowExpander', {
                            rowBodyTpl: [
                                'rowBodyTpl'
                            ]
                        })
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});